FROM ubuntu:16.04 as base

RUN apt-get update && apt-get install -y wget && apt-get -y upgrade
RUN apt-get install -y python-pip
RUN apt-get install -y python-dev
RUN apt-get install build-essential

RUN groupadd -g 999 appuser && \
    useradd -r -u 999 -g appuser appuser

RUN pip install pycryptodome jwcrypto

RUN pip install redis

WORKDIR /app

RUN wget https://mosquitto.org/files/source/mosquitto-1.3.5.tar.gz

RUN apt-get install -y libc-ares-dev libssl-dev libwrap0-dev uthash-dev uuid-dev

RUN tar -xvzf mosquitto-1.3.5.tar.gz

ADD /ingestion/mosquitto-auth /app/mosquitto-1.3.5

WORKDIR /app/mosquitto-1.3.5

RUN make

RUN make install

RUN ls

WORKDIR /app

RUN ls -la


WORKDIR /app/mosquitto-1.3.5/mosquitto_jwt_auth

RUN ./build.sh

WORKDIR /app/mosquitto-1.3.5

EXPOSE 8883

RUN echo "user root" >> /app/mosquitto-1.3.5/mosquitto.conf

RUN echo "auth_plugin   /app/mosquitto-1.3.5/mosquitto_jwt_auth/jwt_auth_plugin.so" >> /app/mosquitto-1.3.5/mosquitto.conf

RUN echo "auth_opt_path /app/mosquitto-1.3.5/mosquitto_jwt_auth/" >> /app/mosquitto-1.3.5/mosquitto.conf

RUN echo "port 8883" >> /app/mosquitto-1.3.5/mosquitto.conf

#RUN echo "cafile /app/keys/sslca.crt" >> /app/mosquitto-1.3.5/mosquitto.conf
RUN echo "cafile /app/keys/ssl/server.cert" >> /app/mosquitto-1.3.5/mosquitto.conf

RUN echo "keyfile /app/keys/ssl/server.key" >> /app/mosquitto-1.3.5/mosquitto.conf

RUN echo "certfile /app/keys/ssl/server.cert" >> /app/mosquitto-1.3.5/mosquitto.conf

RUN echo "tls_version tlsv1.2" >> /app/mosquitto-1.3.5/mosquitto.conf


RUN echo "require_certificate false" >> /app/mosquitto-1.3.5/mosquitto.conf

USER appuser

CMD ["/app/mosquitto-1.3.5/src/mosquitto", "-c", "/app/mosquitto-1.3.5/mosquitto.conf"]
