FROM ubuntu:18.04 as base

RUN apt update && apt-get install -y wget
RUN apt update && apt-get install -y python3-pip  python3.8-dev build-essential jq libffi-dev libc-ares-dev libssl-dev libwrap0-dev uthash-dev uuid-dev

RUN groupadd -g 999 appuser && \
    useradd -r -u 999 -g appuser appuser

RUN pip3 install pycryptodome jwcrypto python-keycloak

RUN pip3 install redis

RUN mkdir /app
RUN chown appuser /app

WORKDIR /app

RUN wget https://mosquitto.org/files/source/mosquitto-1.4.15.tar.gz

RUN mkdir mosquitto

RUN tar -xvzf mosquitto-1.4.15.tar.gz -C mosquitto --strip-components 1

ADD /ingestion/mosquitto-auth /app/mosquitto
ADD start-broker.sh /app
ADD wait-for-it.sh /app

WORKDIR /app/mosquitto

RUN make

RUN make install
RUN chown appuser /app/mosquitto/mosquitto.conf
RUN chown appuser /app/mosquitto

WORKDIR /app

WORKDIR /app/mosquitto/mosquitto_jwt_auth

RUN ./build.sh

WORKDIR /app/mosquitto

EXPOSE 8883
USER appuser
CMD ["/app/start-broker.sh"]
