FROM ubuntu:16.04 as base

RUN apt-get update && apt-get install -y wget && apt-get -y upgrade
RUN apt-get install -y python-pip  python-dev build-essential jq libffi-dev libc-ares-dev libssl-dev libwrap0-dev uthash-dev uuid-dev

RUN groupadd -g 999 appuser && \
    useradd -r -u 999 -g appuser appuser

RUN pip install pycryptodome jwcrypto

RUN pip install redis

RUN mkdir /app
RUN chown appuser /app

WORKDIR /app

RUN wget https://mosquitto.org/files/source/mosquitto-1.3.5.tar.gz

RUN mkdir mosquitto

RUN tar -xvzf mosquitto-1.3.5.tar.gz -C mosquitto --strip-components 1

ADD /ingestion/mosquitto-auth /app/mosquitto
ADD start-broker.sh /app

WORKDIR /app/mosquitto

RUN make

RUN make install
RUN chown appuser /app/mosquitto/mosquitto.conf
RUN chown appuser /app/mosquitto

WORKDIR /app

WORKDIR /app/mosquitto/mosquitto_jwt_auth

RUN ./build.sh

WORKDIR /app/mosquitto

EXPOSE 8883
USER appuser
CMD ["/app/start-broker.sh"]
