FROM mhart/alpine-node:6.13.1

ADD / /app
RUN apk update && apk upgrade && \
    apk add --no-cache bash git openssh
RUN addgroup -g 1001 appuser && \
    adduser -u 1001 -S appuser -G appuser

WORKDIR /app

RUN ls

RUN chmod 777 setup-analytics-gateway.sh

RUN npm install forever node-cache

RUN npm install --production

RUN chmod 777 start-analytics-gateway.sh wait-for-it.sh

USER appuser
ENTRYPOINT ["/bin/sh","start-analytics-gateway.sh"]
